### ISSUE TITLE
Regolith 2 with the Catppuccin Mocha theme applied is in Light Mode

### ISSUE THREAD

**Issue by josh5555s** [taka0o/regolith#6]
All of the programs that are set to match system light or dark mode settings are in light mode when Catppuccin Mocha is applied. The theme otherwise appears correct.

My assumption is that Catppuccin Mocha should be considered a dark mode theme.

Thanks for the help. I love the theme.

**Comment by sbmueller** [comment]
I think you also need to install the gtk theme:
https://github.com/catppuccin/gtk

**Comment by josh5555s** [comment]
You called it!
I had missed the Dependencies section of the README.md. Once I installed those, it resolved the issue.

Thank you for the guidance.
